//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 12:06:21 PM IST 
//


package nokia.example.gradle.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nokia.example.gradle.wsdl package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nokia.example.gradle.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetServersRequest }
     * 
     */
    public GetServersRequest createGetServersRequest() {
        return new GetServersRequest();
    }

    /**
     * Create an instance of {@link GetServersResponse }
     * 
     */
    public GetServersResponse createGetServersResponse() {
        return new GetServersResponse();
    }

    /**
     * Create an instance of {@link ServerSoap }
     * 
     */
    public ServerSoap createServerSoap() {
        return new ServerSoap();
    }

}
